apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: nextjs-sample-app-pipeline-
      spec:
        pipelineRef:
          name: nextjs-sample-app
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: another-sample-app
          - name: source-repo
            value: https://github.com/cloud-native-garage-method-cohort/nextjs-sample-app-fred
          - name: image-repo
            value: quay.io/frederic_dutheil_fr/nextjs-sample-app-fred
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
